# fly.toml app configuration file generated for exch-gr-strapi on 2024-07-03T17:01:21-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'exch-gr-strapi'
primary_region = 'ewr'

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 1337
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']
#  force_https = true

[deploy]
  strategy = "canary"

[processes]
  app = "yarn start"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
	processes = ['app']

[env]
	APP_NAME = 'exch-gr-strapi'
	CLOUDFLARE_ACCOUNT_ID = 'ab8348285fec6024f2b02050bdfb2243'
	CLOUDFLARE_ZONE_ID = 'bf63f4dc453ca15d5cbe87ba5fabd599'
	CONTAINER_PORT = '1337'
	DATABASE_CLIENT = 'postgres'
	DATABASE_NAME = 'exchgr'
	DATABASE_PORT = '5432'
	DATABASE_SSL = 'false'
	DATABASE_USERNAME = 'root'
	DOMAIN_NAME = 'exch.gr'
	HOST = '0.0.0.0'
