mapRoles: |
  - groups:
    - system:bootstrappers
    - system:nodes
    rolearn: arn:aws:iam::${aws_account_id}:role/${eks_node_group_role_name}
    username: system:node:{{EC2PrivateDNSName}}
mapUsers: |
  - groups:
    - system:masters
    userarn: arn:aws:iam::${aws_account_id}:root
