apiVersion: apps/v1
kind: Deployment
metadata:
  name: $APP_NAME
spec:
  selector:
    matchLabels:
      run: $APP_NAME
  replicas: 1
  template:
    metadata:
      labels:
        run: $APP_NAME
    spec:
      containers:
        - name: $APP_NAME
          image: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$APP_NAME
          resources:
            requests:
              memory: 512Mi
            limits:
              memory: 1Gi
          ports:
            - containerPort: $PORT
          env:
            - name: HOST
              value: "${HOST}"
            - name: PORT
              value: "${PORT}"
            - name: APP_KEYS
              value: "${APP_KEYS}"
            - name: API_TOKEN_SALT
              value: "${API_TOKEN_SALT}"
            - name: ADMIN_JWT_SECRET
              value: "${ADMIN_JWT_SECRET}"
            - name: DATABASE_CLIENT
              value: "${DATABASE_CLIENT}"
            - name: DATABASE_HOST
              value: "${DATABASE_HOST}"
            - name: DATABASE_PORT
              value: "${DATABASE_PORT}"
            - name: DATABASE_NAME
              value: "${DATABASE_NAME}"
            - name: DATABASE_USERNAME
              value: "${DATABASE_USERNAME}"
            - name: DATABASE_PASSWORD
              value: "${DATABASE_PASSWORD}"
            - name: DATABASE_SSL
              value: "${DATABASE_SSL}"
            - name: JWT_SECRET
              value: "${JWT_SECRET}"
