apiVersion: apps/v1
kind: Deployment
metadata:
  name: $APP_NAME
spec:
  selector:
    matchLabels:
      run: $APP_NAME
  replicas: 1
  template:
    metadata:
      labels:
        run: $APP_NAME
    spec:
      containers:
        - name: $APP_NAME
          image: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$APP_NAME
          resources:
            requests:
              memory: 512Mi
            limits:
              memory: 1Gi
          ports:
            - containerPort: 1337
