apiVersion: v1
kind: Service
metadata:
  name: $APP_NAME
  labels:
    run: $APP_NAME
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb-ip"
spec:
  ports:
    - port: 443
      protocol: TCP
  selector:
    run: $APP_NAME
