apiVersion: v1
kind: Service
metadata:
  name: $APP_NAME
  labels:
    run: $APP_NAME
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb-ip"
    service.beta.kubernetes.io/aws-load-balancer-eip-allocations: "$ELASTIC_IP_ALLOCATION_ID_EXCH_GR_US_EAST_1A,$ELASTIC_IP_ALLOCATION_ID_EXCH_GR_US_EAST_1B"
spec:
  type: LoadBalancer
  ports:
    - port: 443
      protocol: TCP
  selector:
    run: $APP_NAME
