name: Deploy
run-name: "${{ github.actor }} is deploying: ${{ github.event.head_commit.message }}"
on:
  push:
    branches:
      - 'main'
env:
  AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
  AWS_REGION: ${{ vars.AWS_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  APP_NAME: ${{ vars.APP_NAME }}
  CONTAINER_PORT: ${{ vars.CONTAINER_PORT }}
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
  CLOUDFLARE_ACCOUNT_ID: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    env:
      ADMIN_CNAME: ${{ vars.ADMIN_CNAME }}
    steps:
      - name: "checkout"
        uses: actions/checkout@v4
      - name: "setup terraform"
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
      - name: "authenticate with aws"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
      - name: "cache terraform state"
        id: cache
        uses: actions/cache@v4
        with:
          key: ${{ hashFiles('terraform/**') }}
          path: |
            terraform/.terraform
            terraform/.terraform.lock.hcl
      - name: "terraform init"
        if: steps.cache.outputs.cache-hit != 'true'
        run: terraform init -backend-config="bucket=$APP_NAME-terraform" -backend-config="key=terraform-state" -backend-config="region=$AWS_REGION"
      - name: "terraform apply"
        if: steps.cache.outputs.cache-hit != 'true'
        run: terraform apply -auto-approve
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    needs: deploy-infra
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
