name: Deploy
run-name: ${{ github.actor }} is deploying
on:
  push:
    branches:
      - 'main'
jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: "checkout"
        uses: actions/checkout@v3
      - name: "setup terraform"
        uses: hashicorp/setup-terraform@v2
      - name: "authenticate with aws"
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: "terraform init"
        run: terraform init
      - name: "terraform apply"
        run: terraform apply -auto-approve
  build-and-push-image:
    needs: deploy-infra
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG_BASE: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/exch-gr-strapi
    steps:
      - name: "checkout"
        uses: actions/checkout@v3
      - name: "authenticate with aws"
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: "log into ecr"
        uses: aws-actions/amazon-ecr-login@v1
      - name: "pull previous image"
        continue-on-error: true
        run: docker pull ${{ env.IMAGE_TAG_BASE }}
      - name: "build image"
        run: |
          docker build -t ${{ env.IMAGE_TAG_BASE }} .
          docker tag ${{ env.IMAGE_TAG_BASE }} ${{ env.IMAGE_TAG_BASE }}:${{ github.sha }}
      - name: "push image"
        run: |
          docker push ${{ env.IMAGE_TAG_BASE }}:${{ github.sha }}
          docker push ${{ env.IMAGE_TAG_BASE }}:latest
